/* styleguide.js — generated by scripts/build-styleguide.py.
   Three jobs, each of which would otherwise need an inline attribute:
     1. the dark-mode toggle
     2. printing each token's COMPUTED value, so the tables cannot go stale
     3. applying demo-only widths (progress bars) and swatch colours */
(function () {
  'use strict';

  document.addEventListener('click', function (e) {
    var btn = e.target.closest('[data-theme-toggle]');
    if (!btn) return;
    var h = document.documentElement;
    var next = h.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    h.setAttribute('data-theme', next);
    try { localStorage.setItem('ns-theme', next); } catch (err) {}
  });

  function paint() {
    var cs = getComputedStyle(document.documentElement);
    document.querySelectorAll('.sg-token-val').forEach(function (el) {
      el.textContent = cs.getPropertyValue(el.dataset.token).trim() || '\u2014';
    });
    document.querySelectorAll('[data-swatch]').forEach(function (el) {
      el.style.background = 'var(' + el.dataset.swatch + ')';
    });
    document.querySelectorAll('[data-demo-width]').forEach(function (el) {
      el.style.width = el.dataset.demoWidth + '%';
    });
  }
  if (document.readyState !== 'loading') paint();
  else document.addEventListener('DOMContentLoaded', paint);
})();
