#!/usr/bin/env python3
"""
subset-icons.py — build a self-hosted, subsetted Phosphor icon font.

WHY
    The theme used to load Phosphor from unpkg: two render-blocking
    stylesheets (164 KB) plus two webfonts (279 KB) = ~443 KB from a
    third-party origin, to draw ~123 icons out of ~1,530. This script keeps
    only the glyphs the theme actually references and emits a local CSS file,
    so nothing renders-blocks on a CDN we don't control.

WHAT IT WRITES
    assets/fonts/phosphor-subset.woff2       (regular weight)
    assets/fonts/phosphor-fill-subset.woff2  (fill weight)
    assets/css/0-foundation/icons.css               @font-face + only the used classes

WHEN TO RE-RUN
    Any time you add a new `ph-*` class to a template, OR add an icon to a
    Ghost POST that isn't already in the subset. See CONTENT_SAFELIST below —
    icons used inside post content cannot be discovered by scanning templates,
    so they must be listed there by hand.

        python3 scripts/subset-icons.py

    Requires: pip3 install fonttools brotli
    The OUTPUT is committed, so a normal `yarn build` never needs Python.
"""

import json
import os
import re
import subprocess
import sys
import tempfile

from glob import glob

PHOSPHOR_VERSION = "2.1.2"
CDN = f"https://unpkg.com/@phosphor-icons/web@{PHOSPHOR_VERSION}/src"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "assets", "css", "0-foundation", "icons.css")

# Icons used inside Ghost POST CONTENT rather than in templates. Template
# scanning cannot see these, so anything an author drops into a post as
# <i class="ph ph-foo"> must be added here or it will render as a blank box.
# Keep this list short and deliberate — every entry costs bytes.
CONTENT_SAFELIST = [
    "ph-info", "ph-warning", "ph-warning-circle", "ph-check-circle",
    "ph-x-circle", "ph-lightbulb", "ph-note", "ph-bookmark-simple",
    "ph-code", "ph-terminal-window", "ph-database", "ph-cloud",
    "ph-lightning", "ph-rocket-launch", "ph-star", "ph-question",
]

WEIGHTS = [
    # (weight dir on the CDN, font file, family name, output basename, class prefix)
    ("regular", "Phosphor.woff2", "Phosphor", "phosphor-subset", "ph"),
    ("fill", "Phosphor-Fill.woff2", "Phosphor-Fill", "phosphor-fill-subset", "ph-fill"),
]


def fetch(url):
    """Fetch via curl rather than urllib: python.org macOS builds ship without
    a configured CA bundle, so urllib raises CERTIFICATE_VERIFY_FAILED on a
    machine where curl works fine."""
    out = subprocess.run(
        ["curl", "-sSLf", url], check=True, stdout=subprocess.PIPE
    )
    return out.stdout


def used_icon_classes():
    """Every `ph-*` class literal appearing in theme source."""
    sources = (
        glob(os.path.join(ROOT, "*.hbs"))
        + glob(os.path.join(ROOT, "partials", "**", "*.hbs"), recursive=True)
        + glob(os.path.join(ROOT, "assets", "css", "**", "*.css"), recursive=True)
        + glob(os.path.join(ROOT, "assets", "js", "**", "*.js"), recursive=True)
    )
    found = set()
    for path in sources:
        # icons.css is our own output; scanning it would make the subset
        # self-perpetuating and impossible to shrink.
        if os.path.abspath(path) == CSS_OUT:
            continue
        with open(path, encoding="utf-8") as fh:
            found.update(re.findall(r"\bph-[a-z0-9-]+", fh.read()))
    found.discard("ph-fill")          # the weight modifier, not an icon
    found.update(CONTENT_SAFELIST)
    return found


def codepoint_map(weight):
    """class name -> codepoint, parsed from Phosphor's own stylesheet."""
    css = fetch(f"{CDN}/{weight}/style.css").decode("utf-8")
    pairs = re.findall(
        r"\.(ph-[a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-fA-F]+)\"", css
    )
    return {name: int(cp, 16) for name, cp in pairs}


def main():
    try:
        import fontTools  # noqa: F401
        import brotli     # noqa: F401
    except ImportError:
        sys.exit("Missing deps. Run:  pip3 install fonttools brotli")

    os.makedirs(FONT_DIR, exist_ok=True)
    wanted = used_icon_classes()
    print(f"{len(wanted)} icon classes referenced (incl. {len(CONTENT_SAFELIST)} safelisted)")

    css_parts = [
        "/* ============================================================================\n"
        "   icons.css — GENERATED by scripts/subset-icons.py. Do not edit by hand.\n"
        "   ----------------------------------------------------------------------------\n"
        f"   Phosphor v{PHOSPHOR_VERSION}, subsetted to only the glyphs this theme uses and\n"
        "   served from our own origin. Re-run the script after adding a new ph-* class.\n"
        "   ========================================================================== */\n"
    ]

    for weight, fontfile, family, out_base, prefix in WEIGHTS:
        cmap = codepoint_map(weight)
        present = sorted(n for n in wanted if n in cmap)
        missing = sorted(n for n in wanted if n not in cmap)
        if missing:
            print(f"  [{weight}] not in this weight, skipped: {', '.join(missing)}")

        codepoints = sorted({cmap[n] for n in present})
        raw = fetch(f"{CDN}/{weight}/{fontfile}")

        with tempfile.NamedTemporaryFile(suffix=".woff2", delete=False) as tmp:
            tmp.write(raw)
            src = tmp.name
        dst = os.path.join(FONT_DIR, out_base + ".woff2")

        subprocess.run(
            [
                sys.executable, "-m", "fontTools.subset", src,
                "--unicodes=" + ",".join(f"U+{c:04X}" for c in codepoints),
                "--flavor=woff2",
                "--layout-features=",
                "--no-hinting",
                "--desubroutinize",
                "--output-file=" + dst,
            ],
            check=True,
        )
        os.unlink(src)

        before, after = len(raw), os.path.getsize(dst)
        print(f"  [{weight}] {len(present)} glyphs · {before/1024:.0f} KB -> {after/1024:.1f} KB")

        css_parts.append(
            f'\n@font-face {{\n'
            f'  font-family: "{family}";\n'
            # The build rebases urls and consumes exactly one "../", so
            # "../../fonts/" here emits "../fonts/" in assets/built/screen.css,
            # which is what resolves to assets/fonts/. Verify after changing.
            f'  src: url("../../fonts/{out_base}.woff2") format("woff2");\n'
            f"  font-weight: normal;\n  font-style: normal;\n"
            # swap, not block: block hides icons behind an invisible-text phase.
            f"  font-display: swap;\n}}\n"
        )
        sel = ".ph" if prefix == "ph" else ".ph-fill"
        css_parts.append(
            f"\n{sel} {{\n"
            f'  font-family: "{family}" !important;\n'
            f"  speak: never;\n  font-style: normal;\n  font-weight: normal;\n"
            f"  font-variant: normal;\n  text-transform: none;\n  line-height: 1;\n"
            f"  -webkit-font-smoothing: antialiased;\n"
            f"  -moz-osx-font-smoothing: grayscale;\n  display: inline-block;\n}}\n\n"
        )
        for name in present:
            css_parts.append(f'{sel}.{name}:before {{ content: "\\{cmap[name]:x}"; }}\n')

    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write("".join(css_parts))
    print(f"wrote {os.path.relpath(CSS_OUT, ROOT)}")


if __name__ == "__main__":
    main()
